// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20230101202132_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "Category",
                            Description = "Description",
                            ImageUrl = "www.google.com",
                            Name = "Name",
                            Price = 50m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Category",
                            Description = "Description",
                            ImageUrl = "www.google.com",
                            Name = "Name",
                            Price = 100m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Category",
                            Description = "Description",
                            ImageUrl = "www.google.com",
                            Name = "Name",
                            Price = 150m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Category",
                            Description = "Description",
                            ImageUrl = "www.google.com",
                            Name = "Name",
                            Price = 200m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Category",
                            Description = "Description",
                            ImageUrl = "www.google.com",
                            Name = "Name",
                            Price = 250m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Category",
                            Description = "Description",
                            ImageUrl = "www.google.com",
                            Name = "Name",
                            Price = 300m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Category",
                            Description = "Description",
                            ImageUrl = "www.google.com",
                            Name = "Name",
                            Price = 350m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Category",
                            Description = "Description",
                            ImageUrl = "www.google.com",
                            Name = "Name",
                            Price = 400m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Category",
                            Description = "Description",
                            ImageUrl = "www.google.com",
                            Name = "Name",
                            Price = 450m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "Category",
                            Description = "Description",
                            ImageUrl = "www.google.com",
                            Name = "Name",
                            Price = 500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
